use_frameworks!

platform :ios, '15.0'

target 'GNestedScrollView_Example' do
  pod 'GNestedScrollView', :path => '../'
  pod 'Masonry'
  target 'GNestedScrollView_Tests' do
    inherit! :search_paths

    
  end
end
